### ISSUE TITLE
Can't open workflows. 

### ISSUE THREAD

**Issue by logdog0411** [PacktPublishing/Data-Engineering-with-Alteryx#1]
Every time I try to open one of your workflows, I get an error saying,  ">" is an unexpected token. The expected token is "=", Line 16, position 76. 

Any ideas? I have tried with multiple workflows and multiple versions of Alteryx.

**Comment by Sivivatu** [comment]
Sounds like when you have downloaded the files, the full file hasn't been downloaded and is corrupt. Can you try downloading again from the home page of the repo > code button > download zip. See image below
![image](https://user-images.githubusercontent.com/7496456/180295986-07da2e68-50fc-4f32-9672-3ee661ecb1a3.png)
