### ISSUE TITLE
Chapter 4 File not found?

### ISSUE THREAD

**Issue by m0onc4k3** [PacktPublishing/Data-Engineering-with-Alteryx#2]
Hi, everyone. ONS_CPI_Dataset_mm23.csv is not present in Chapter 04 folder or am I missing something? Also, shouldn't a relative reference be used?

![imagen_2022-07-28_110952142](https://user-images.githubusercontent.com/108893929/181586204-f819441c-eb04-4fa9-939b-7fce9837094f.png)

**Comment by Sivivatu** [comment]
Hi @jupdiaz,
Thanks for spotting this. the data set was in a separate folder that was missed when adding to the repository.
Additionally, your right, the file references should be relative.
I have made both these changes in commit https://github.com/PacktPublishing/Data-Engineering-with-Alteryx/commit/b61b04f20623a509f5519e6986133913fca7c2b4 
Try out those updates and if they are still a problem please let me know
