### ISSUE TITLE
Chapter 1 - no snowflake

### ISSUE THREAD

**Issue by dkinneyBU** [PacktPublishing/Data-Engineering-with-Alteryx#3]
For the InDB example there is no snowflake database in your repo.

**Comment by saurabhk710** [comment]
Hey @Sivivatu !

can you please help @dkinneyBU ?

**Comment by Sivivatu** [comment]
HI @dkinneyBU, The snowflake database is part of the snowflake sample data. Once you have created an [account](https://signup.snowflake.com/) (you can use a trial with $400 of credits), you will have access to the table SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_RETURN.
